server:
 port: 9191

spring:
 application:
  name: API-GATEWAY
 cloud:
  gateway:
   routes:
    - id: USER-SERVICE
      uri: lb://USER-SERVICE
      predicates:
       - Path=/users/**
      filters:
       - name: CircuitBreaker
         args: 
          name: USER-SERVICE
          fallbackuri: forward:/userServiceFallBack
    - id: USERGROUP-SERVICE
      uri: lb://USERGROUP-SERVICE
      predicates:
       - Path=/usergroups/**
      filters:
       - name: CircuitBreaker
         args: 
          name: USER-SERVICE
          fallbackuri: forward:/userGroupServiceFallBack
    - id: POLICY-SERVICE
      uri: lb://POLICY-SERVICE
      predicates:
       - Path=/policies/**
      filters:
       - name: CircuitBreaker
         args: 
          name: USER-SERVICE
          fallbackuri: forward:/policyServiceFallBack

hystrix:
 command:
  fallbackcmd:
   execution:
    isolation:
     thread:
      timeoutInMilliseconds: 4000

management:
 endpoints:
  web:
   exposure:
    include: '*'
